
# This workflow will build a package using Maven, analyze with SonarCloud, and publish it to GitHub Container Registry (GHCR) using Docker
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
name: Maven CI/CD with SonarCloud and GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Create /etc/gitconfig if not exists
        run: |
          sudo touch /etc/gitconfig
          sudo chmod 644 /etc/gitconfig

      - name: Build with Maven
        run: mvn clean install

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          args: >
            -Dsonar.projectKey=caalzate91_spring-data-jwt
            -Dsonar.organization=caalzate91
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Publish to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build -t ghcr.io/${{ github.repository_owner }}/spring-data-jwt:latest .
          docker push ghcr.io/${{ github.repository_owner }}/spring-data-jwt:latest
